MD004:
  style: dash
MD007:
  # spaces for indent
  indent: 2
  # don't indent the fist level of lists
  start_indented: false
MD013: false
MD029:
  #ordered list style
  style: ordered
MD060:
  style: compact
